return {
	{
		"nvim-treesitter/nvim-treesitter",
		build = ":TSUpdate",
		event = { "VeryLazy" },
		branch = "main",
		cmd = { "TSUpdateSync", "TSUpdate", "TSInstall" },
		opts = {
			grammars = {
				"bash",
				"c",
				"cpp",
				"diff",
				"html",
				"javascript",
				"jsdoc",
				"json",
				"lua",
				"luadoc",
				"luap",
				"markdown",
				"latex",
				"markdown_inline",
				"python",
				"query",
				"regex",
				"toml",
				"tsx",
				"typescript",
				"vim",
				"vimdoc",
				"yaml",
				"go",
				"gomod",
				"gosum",
				"gowork",
				"gowork",
				"gotmpl",
				"astro",
				"cmake",
				"make",
				"matlab",
				"nginx",
				"rasi",
				"sql",
				"arduino",
				"awk",
				"comment",
				"css",
				"dart",
				"desktop",
				"dockerfile",
				"gitcommit",
				"gitignore",
				"jsdoc",
			},
		},
		config = function(_, opts)
			require("nvim-treesitter").install(opts.grammars)
		end,
	},
	{
		"nvim-treesitter/nvim-treesitter-textobjects",
		branch = "main",
		event = { "VeryLazy" },
		init = function()
			vim.g.no_plugin_maps = true
		end,
		opts = {},
	},
	{
		"nvim-treesitter/nvim-treesitter-context",
		event = { "VeryLazy" },
		opts = { mode = "cursor", max_lines = 3 },
	},
}
