# Plugins configuration for Tmux
# 
# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-copycat'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-logging'
set -g @plugin 'tmux-plugins/tmux-cowboy' # kill process in pane prefix+*
set -g @plugin 'laktak/extrakto'

# vi mode
set -g mode-keys vi
set -g status-keys vi

# key bindings
#
# switch session with fzf
bind S display-popup -E "tmux list-sessions | sed -E 's/:.*$//' | grep -v \"^$(tmux display-message -p '#S')\$\" | fzf --reverse | xargs tmux switch-client -t"
# bring up tmux-sessionizer
bind f display-popup -E "$HOME/scripts/tmux-sessionizer"
# toggle status
bind-key b set-option status
# reload tmux config
bind r source-file $XDG_CONFIG_HOME/tmux/tmux.conf \; display-message "Config reloaded..."

# options
# do not detach after killing a session
set-option -g detach-on-destroy off
set-option -g focus-events on # to make 'autoread' work in neovim.
set-option -a terminal-features ':RGB'
# make colors look real in Neovim or any terminal application
set -g default-terminal "screen-256color"
set-option -ga terminal-overrides ",screen-256color:Tc"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '$XDG_CONFIG_HOME/tmux/plugins/tpm/tpm'
